nelmio_cors:
    defaults:
        origin_regex: true
        allow_origin: ['%env(CORS_ALLOW_ORIGIN)%']
        allow_methods: ['GET', 'OPTIONS', 'POST', 'PUT', 'PATCH', 'DELETE']
        allow_headers: ['Accept', 'Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        forced_allow_origin_value: ~
    paths:
        '^/api/': ~
