api_login_check:
    path:     /api/login_check
    methods:  [POST]

api_regiser:
    path:     /api/register
    methods:  [POST]

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }
